### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by MorganWeiss** [huangyunict/redfin_houses#1]
Can you include some examples of how to use your class?

**Comment by rpetrenko** [comment]
i created a basic example: https://github.com/rpetrenko/redfin_houses/blob/master/examples/example1.py

**Comment by Narzard** [comment]
Your zip code in example works fine, but mine (23451) throws an error. Any ideas why that is?

```
Searching within zipcode: 23451
Applying filter: filter/property-type=house,max-price=800k
Traceback (most recent call last):
  File "examples/example1.py", line 28, in <module>
    df_houses = convert_csv_to_dataframe(houses_csv)
  File "examples/example1.py", line 10, in convert_csv_to_dataframe
    df = pd.read_csv(f)
  File "C:\Users\Benj\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Benj\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\Benj\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "C:\Users\Benj\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\Benj\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by rpetrenko** [comment]
just forget it, it turned out, redfin is very smart to block bots... so, just after tens or calls they detect it and might even block you.  try to open web, check if it already requires you to confirm you aren't a machine.
